Update gitflow-avh 1.10.1->1.11.0

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -1,4 +1,5 @@
-#@IgnoreInspection BashAddShebang
+# $Id$
+# vim:et:ft=sh:sts=2:sw=2
 #
 # git-flow -- A collection of Git extensions to provide high-level
 # repository operations for Vincent Driessen's branching model.
@@ -10,7 +11,7 @@
 #    http://github.com/petervanderdoes/gitflow
 #
 # Authors:
-# Copyright 2012-2016 Peter van der Does. All rights reserved.
+# Copyright 2012-2017 Peter van der Does. All rights reserved.
 #
 # Original Author:
 # Copyright 2010 Vincent Driessen. All rights reserved.
@@ -258,14 +259,14 @@ no-ff!                 Never fast-forward during the merge
 	DEFINE_boolean 'fetch' false "fetch from $ORIGIN before performing finish" F
 	DEFINE_boolean 'rebase' false "rebase before merging" r
 	DEFINE_boolean 'preserve-merges' false 'try to recreate merges while rebasing' p
-	DEFINE_boolean 'push' false "push to $ORIGIN after performing finish" P
+	DEFINE_boolean 'push' false "push to $ORIGIN after performing finish"
 	DEFINE_boolean 'keep' false "keep branch after performing finish" k
-	DEFINE_boolean 'keepremote' false "keep the remote branch" R
-	DEFINE_boolean 'keeplocal' false "keep the local branch" L
+	DEFINE_boolean 'keepremote' false "keep the remote branch"
+	DEFINE_boolean 'keeplocal' false "keep the local branch"
 	DEFINE_boolean 'force_delete' false "force delete feature branch after finish" D
 	DEFINE_boolean 'squash' false "squash feature during merge" S
-	DEFINE_boolean 'squash-info' false "add branch info during squash" s
-	DEFINE_boolean 'no-ff!' false "Don't fast-forward ever during merge " m
+	DEFINE_boolean 'squash-info' false "add branch info during squash"
+	DEFINE_boolean 'no-ff!' false "Don't fast-forward ever during merge "
 
 	# Override defaults with values from config
 	gitflow_override_flag_boolean   "feature.finish.fetch"             "fetch"
@@ -372,9 +373,9 @@ no-ff!                 Never fast-forward during the merge
 		if flag preserve_merges; then
 			_rebase_opts="$_rebase_opts -p"
 		fi
-#		if flag showcommands; then
-#			_rebase_opts="$_rebase_opts --showcommands"
-#		fi
+		if flag showcommands; then
+			_rebase_opts="$_rebase_opts --showcommands"
+		fi
 		if ! git flow feature rebase $_rebase_opts "$NAME"; then
 			warn "Finish was aborted due to conflicts during rebase."
 			warn "Please finish the rebase manually now."
@@ -612,10 +613,11 @@ showcommands!    Show git commands while executing them
 	# Parse arguments
 	parse_args "$@"
 
-	warn "The command 'git flow feature checkout/co' will be deprecated per version 2.0.0"
-	gitflow_require_name_arg
-
-	git_do checkout "$BRANCH"  || die "Could not check out branch '$BRANCH'."
+	NAME=$(gitflow_resolve_nameprefix "$NAME" "$PREFIX")
+	if [ $? -eq 0 ]; then
+		BRANCH=$PREFIX$NAME
+		git_do checkout "$BRANCH"  || die "Could not check out branch '$BRANCH'."
+	fi
 }
 
 cmd_co() {
@@ -657,7 +659,10 @@ p,[no]preserve-merges  Preserve merges
 	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
 
 	warn "Will try to rebase '$NAME' which is based on '$BASE_BRANCH'..."
-	require_clean_working_tree
+	if ! git_config_bool_exists "rebase.autostash"; then
+		require_clean_working_tree
+	fi
+
 	require_branch "$BRANCH"
 
 	git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't rebase the feature branch '$BRANCH'."
@@ -801,13 +806,13 @@ r,[no]remote     Delete remote branch
 	if git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
 		git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
 		if flag remote; then
-			git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+			git_remote_branch_delete "$BRANCH"
 		fi
 	else
 		if flag force; then
 			git_do branch -D "$BRANCH" || die "Could not delete the $BRANCH."
 			if flag remote; then
-				git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+				git_remote_branch_delete "$BRANCH"
 			fi
 		else
 			die "Feature branch '$BRANCH' has been not been merged yet. Use -f to force the deletion."
@@ -823,4 +828,16 @@ r,[no]remote     Delete remote branch
 	flag remote && echo "- Feature branch '$BRANCH' in '$ORIGIN' has been deleted."
 	echo "- You are now on branch '$(git_current_branch)'"
 	echo
+}
+
+cmd_rename() {
+	OPTIONS_SPEC="\
+git flow feature rename <new_name> [<new_name>]
+
+Rename a given feature branch
+--
+h,help!          Show this help
+showcommands!    Show git commands while executing them
+"
+	gitflow_rename_branch "$@"
 }
